CREATE TABLE [dbo].[DeletedServices](
	[DeletedDate] [datetime] NULL,
	[UserDelete] [int] NULL,
	[LastLine] [int] NULL,
	[State] [varchar](100) NULL,
	[InvoiceNo] [int] NOT NULL,
	[DayDate] [datetime] NULL,
	[DrId] [int] NULL,
	[CsId] [int] NULL,
	[DrValue] [float] NULL,
	[CsValue] [float] NULL,
	[CoValue] [float] NULL,
	[Value] [float] NULL,
	[ServiceGroupId] [int] NULL,
	[ServiceTypeId] [int] NULL,
	[CaseId] [int] NULL,
	[Canceled] [int] NULL,
	[Notes] [nvarchar](1000) NULL,
	[UserName] [int] NULL,
	[MyGetDate] [datetime] NULL,
	[SerialId] [int] NULL,
	[Payed] [float] NULL,
	[Remaining] [float] NULL,
	[Done] [int] NULL,
	[RemainingDate] [datetime] NULL,
	[EmpIdReservation] [int] NULL,
	[EmpIdRemaining] [int] NULL,
	[EmpIdCanceled] [int] NULL,
	[CanceledDate] [datetime] NULL,
	[SerialId2] [int] NULL,
	[Returned] [int] NULL,
	[ReturnedDate] [datetime] NULL,
	[EmpIdReturned] [int] NULL,
	[IsEditing] [int] NULL,
	[MyLine] [int] ,
	[IsClosed] [int] NULL,
	[CompanyId] [bigint] NULL,
	[PreValue] [float] NULL,
	[PrePayed] [float] NULL,
	[PreRemaining] [float] NULL,
	[Qty] [float] NULL,
	[CurrentShift] [bigint] NULL,
	[InsertedDate] [datetime] NULL,
	[RefereId] [bigint] NULL,
	[Flag] [int] NOT NULL,
	[CaseInvoiceNo] [bigint] NOT NULL
)