

CREATE TABLE [dbo].[DeletedItems](
	[DeletedDate] [datetime] NULL,
	[UserDelete] [int] NULL,
	[LastLine] [int] NULL,
	[State] [varchar](100) NULL,

	[Id] [int] NOT NULL,
	[Name] [nvarchar](1000) NULL,
	[GroupId] [int] NULL,
	[TypeId] [int] NULL,
	[PrintingGroupId] [int] NULL,
	[StoreId] [int] NULL,
	[Unit] [nvarchar](1000) NULL,
	[UnitCount] [float] NULL,
	[PurchasePrice] [float] NULL,
	[PurchasePriceSub] [float] NULL,
	[SalesPrice] [float] NULL,
	[SalesPriceSub] [float] NULL,
	[ItemType] [int] NULL,
	[Image] [image] NULL,
	[UnitSub] [nvarchar](1000) NULL,
	[UserName] [int] NULL,
	[MyGetDate] [datetime] NULL,
	[Adding] [int] NULL,
	[IsTables] [int] NULL,
	[IsTakeAway] [int] NULL,
	[IsDelivary] [int] NULL,
	[UnitCount2] [float] NULL,
	[PurchasePriceSub2] [float] NULL,
	[SalesPriceSub2] [float] NULL,
	[UnitSub2] [nvarchar](1000) NULL,
	[Limit] [float] NULL,
	[SizeId] [int] NULL,
	[ColorId] [int] NULL,
	[Barcode] [nvarchar](100) NULL,
	[IsStopped] [int] NULL,
	[Flag] [int] NULL,
	[EnName] [nvarchar](100) NULL,
	[ImportPrice] [float] NULL,
	[ImportPriceSub] [float] NULL,
	[ImportPriceSub2] [float] NULL,
	[IsKidneysWash] [int] NULL,
	[ItemUnitId] [int] NULL,
	[CodeOnPackage] [nvarchar](100) NULL,
	[IsService] [int] NULL,
	[CountryId] [bigint] NULL,
	[AllowEditSalesPrice] [int] NULL,
	[Bonus] [float] NULL,
	[Target] [float] NULL,
	[LimitSub] [float] NULL,
	[Maximum] [int] NULL,
	[MaximumSub] [int] NULL,
	[Stopped] [int] NOT NULL,
	[IsHiddenFromLimit] [int] NOT NULL,
	[SystemUser] [int] NOT NULL,
	[UpdateDate] [datetime] NOT NULL,
	[Notes] [nvarchar](1000) NOT NULL,
	[BoardId] [int] NOT NULL,
	[SubjectLevelId] [int] NOT NULL,
	[SubjectId] [int] NOT NULL,
	[TeacherId] [int] NOT NULL,
	[itemCode] [nvarchar](100) NOT NULL,
	[TaxApi_UnitTypeId] [nvarchar](100) NULL,
	[TaxApi_UnitTypeQty] [float] NULL
) 