create table Hours(Id int)
go
delete Hours
insert Hours select 1
insert Hours select 2
insert Hours select 3
insert Hours select 4
insert Hours select 5
insert Hours select 6
insert Hours select 7
insert Hours select 8
insert Hours select 9
insert Hours select 10
insert Hours select 11
insert Hours select 12
go
create table Minutes(Id int)
go
delete Minutes
insert Minutes select 0
insert Minutes select 1
insert Minutes select 2
insert Minutes select 3
insert Minutes select 4
insert Minutes select 5
insert Minutes select 6
insert Minutes select 7
insert Minutes select 8
insert Minutes select 9
insert Minutes select 10
insert Minutes select 11
insert Minutes select 12
insert Minutes select 13
insert Minutes select 14
insert Minutes select 15
insert Minutes select 16
insert Minutes select 17
insert Minutes select 18
insert Minutes select 19
insert Minutes select 20
insert Minutes select 21
insert Minutes select 22
insert Minutes select 23
insert Minutes select 24
insert Minutes select 25
insert Minutes select 26
insert Minutes select 27
insert Minutes select 28
insert Minutes select 29
insert Minutes select 30
insert Minutes select 31
insert Minutes select 32
insert Minutes select 33
insert Minutes select 34
insert Minutes select 35
insert Minutes select 36
insert Minutes select 37
insert Minutes select 38
insert Minutes select 39
insert Minutes select 40
insert Minutes select 41
insert Minutes select 42
insert Minutes select 43
insert Minutes select 44
insert Minutes select 45
insert Minutes select 46
insert Minutes select 47
insert Minutes select 48
insert Minutes select 49
insert Minutes select 50
insert Minutes select 51
insert Minutes select 52
insert Minutes select 53
insert Minutes select 54
insert Minutes select 55
insert Minutes select 56
insert Minutes select 57
insert Minutes select 58
insert Minutes select 59
